/// Lightweight offline translation engine for the CareBridge narration
/// pipeline. Bridges the reviewed SpeechBank entries with a neural ONNX model
/// (Hausa, Twi) and a domain-specific phrase dictionary (all 3 languages)
/// to translate dynamic text that the narration composes at runtime.
////// Architecture (chained, first-match wins):
///   1. SpeechBank exact clip → reviewed translation
///   2. Neural model (cached) → ONNX MarianMT inference
///   3. Phrase dictionary → greedy longest-match substitution
///
/// Neural inference is async (~170 ms per sentence on-device); results are
/// cached and served synchronously on subsequent calls. The UI "warms"
/// translations when narration text is generated, so by the time the user
/// reads or hears it, the translation is ready.
///
/// On web (no dart:ffi), neural inference is unavailable — falls through to
/// the phrase dictionary. Dagbani has no open model → always dictionary.
library;

import '../i18n/translation_dictionary.dart';
import 'neural_translation_service.dart';

/// How a translation was produced — lets the UI show honest provenance.
enum TranslationSource {
  /// Exact match in the reviewed SpeechBank.
  speechBank,

  /// Generated by the on-device neural translation model (ONNX MarianMT).
  neuralModel,

  /// Composed from the phrase dictionary at runtime.
  phraseDictionary,

  /// No translation available; caller should show English.
  unavailable,
}

class TranslationResult {
  const TranslationResult({
    required this.text,
    required this.source,
    required this.language,
    this.coverage = 0.0,
  });

  final String text;
  final TranslationSource source;
  final String language;

  /// Fraction of input words that were translated (0.0–1.0). Low coverage
  /// means the output is mostly English with a few translated terms.
  final double coverage;

  bool get isDraft => language != 'English';

  /// Whether this translation came from the neural model.
  bool get isNeural => source == TranslationSource.neuralModel;
}

abstract interface class TranslationBackend {
  TranslationResult? translate(String english, String language);
}

/// Phrase-dictionary backend: greedy longest-match substitution.
class _PhraseDictionaryBackend implements TranslationBackend {
  @override
  TranslationResult? translate(String english, String language) {
    if (language == 'English') {
      return TranslationResult(
        text: english,
        source: TranslationSource.speechBank,
        language: 'English',
        coverage: 1.0,
      );
    }

    final input = english.trim();
    if (input.isEmpty) return null;

    final words = input.split(RegExp(r'\s+'));
    final translatedWords = <String>[];
    var translatedCount = 0;
    var i = 0;

    while (i < words.length) {
      String? bestMatch;
      TranslationEntry? bestEntry;

      // Greedy longest match from the current position.
      for (final entry in TranslationDictionary.byLength) {
        final entryWords = entry.english.split(RegExp(r'\s+'));
        if (i + entryWords.length > words.length) continue;

        var matches = true;
        for (var j = 0; j < entryWords.length; j++) {
          if (!_wordEquals(words[i + j], entryWords[j])) {
            matches = false;
            break;
          }
        }

        if (matches) {
          bestMatch = entry.textFor(language);
          bestEntry = entry;
          break; // byLength is sorted longest-first, so first match wins
        }
      }

      if (bestMatch != null && bestEntry != null) {
        translatedWords.add(bestMatch);
        translatedCount += bestEntry.english.split(RegExp(r'\s+')).length;
        i += bestEntry.english.split(RegExp(r'\s+')).length;
      } else {
        // Keep the English word as-is.
        translatedWords.add(words[i]);
        i++;
      }
    }

    final result = translatedWords.join(' ');
    final coverage = words.isEmpty ? 0.0 : translatedCount / words.length;

    // If coverage is too low, the translation is mostly English — not useful.
    if (coverage < 1.0) return null;

    return TranslationResult(
      text: result,
      source: TranslationSource.phraseDictionary,
      language: language,
      coverage: coverage,
    );
  }

  bool _wordEquals(String a, String b) {
    String normalize(String s) =>
        s.toLowerCase().replaceAll(RegExp(r'[^\w\s]'), '').trim();
    return normalize(a) == normalize(b);
  }
}

/// Offline translation service. Singleton; caches results per (text, language).
class TranslationService {
  TranslationService._({
    TranslationBackend? backend,
    NeuralTranslationService? neural,
  }) : _backend = backend ?? _PhraseDictionaryBackend(),
       _neural = neural ?? NeuralTranslationService.instance;

  static TranslationService? _instance;

  static TranslationService get instance =>
      _instance ??= TranslationService._();

  /// Test-only: replace the singleton.
  static TranslationService debugCreate({
    TranslationBackend? backend,
    NeuralTranslationService? neural,
  }) =>
      TranslationService._(backend: backend, neural: neural);

  final TranslationBackend _backend;
  final NeuralTranslationService _neural;
  final _cache = <String, TranslationResult>{};
  static const _maxCacheSize = 500;

  /// Translate [english] into [language]. Returns null if no translation
  /// is available (caller should show English).
  ///
  /// Checks the SpeechBank first for exact clip matches, then falls back
  /// to the phrase dictionary. Results are cached.
  TranslationResult? translate(String english, String language) {
    final lang = _canonicalize(language);
    if (lang == 'English') {
      return TranslationResult(
        text: english,
        source: TranslationSource.speechBank,
        language: 'English',
        coverage: 1.0,
      );
    }

    final cacheKey = '$english|$lang';
    final cached = _cache[cacheKey];
    if (cached != null) return cached;

    // Priority 1: Check neural model cache (populated by warmTranslation).
    final neural = _neural.translateSync(
      english,
      lang,
    );
    if (neural != null && neural.isNotEmpty) {
      final result = TranslationResult(
        text: neural,
        source: TranslationSource.neuralModel,
        language: lang,
        coverage: 1.0,
      );
      _putCache(cacheKey, result);
      return result;
    }

    // Priority 2: Phrase dictionary fallback.
    final result = _backend.translate(english, lang);
    if (result != null) {
      _putCache(cacheKey, result);
    }
    return result;
  }

  /// Async translation that awaits the neural model if not yet cached.
  /// Use this when the caller can tolerate a short delay (~200 ms) and
  /// needs a definitive result before proceeding (e.g. TTS text prep).
  Future<TranslationResult?> translateAsync(
    String english,
    String language,
  ) async {
    final lang = _canonicalize(language);
    // Try sync path first (covers cache hits + dictionary).
    final sync = translate(english, language);
    if (sync != null && sync.source == TranslationSource.neuralModel) {
      return sync;
    }
    // Kick off neural inference if supported.
    if (_neural.supportsLanguage(lang)) {
      final neural = await _neural.warmTranslation(
        english,
        lang,
      );
      if (neural != null && neural.isNotEmpty) {
        final result = TranslationResult(
          text: neural,
          source: TranslationSource.neuralModel,
          language: lang,
          coverage: 1.0,
        );
        _putCache('$english|$lang', result);
        return result;
      }
    }
    return sync;
  }

  /// Pre-warm the neural cache for text that will be displayed shortly.
  /// Fire-and-forget: callers don't await this. By the time the widget
  /// rebuilds, the translation is available via the sync [translate].
  void warmNeural(String english, String language) {
    final lang = _canonicalize(language);
    if (!_neural.supportsLanguage(lang)) return;
    // Skip if dictionary already has high-confidence coverage.
    final dictResult = _backend.translate(english, lang);
    if (dictResult != null && dictResult.isNeural) return;
    // Fire-and-forget neural inference.
    NeuralTranslationService.instance.warmTranslation(english, lang).then((
      result,
    ) {
      if (result != null && result.isNotEmpty) {
        final key = '$english|$lang';
        _cache[key] = TranslationResult(
          text: result,
          source: TranslationSource.neuralModel,
          language: lang,
          coverage: 1.0,
        );
      }
    });
  }

  /// Check if a translation is available without computing it.
  bool hasTranslation(String english, String language) {
    return translate(english, language) != null;
  }

  void _putCache(String key, TranslationResult result) {
    if (_cache.length >= _maxCacheSize) {
      _cache.remove(_cache.keys.first);
    }
    _cache[key] = result;
  }

  String _canonicalize(String language) {
    final value = language.trim().toLowerCase().replaceAll('_', '-');
    if (value == 'english' || value == 'en' || value.startsWith('en-')) {
      return 'English';
    }
    return switch (value) {
      'tw' || 'twi' => 'Twi',
      'dag' || 'dagbani' => 'Dagbani',
      'ha' || 'hausa' => 'Hausa',
      _ => language,
    };
  }
}
