/// Domain-specific medical phrase dictionary for the lightweight offline
/// translation engine. Maps English terms and short phrases to their
/// draft Hausa, Twi, and Dagbani equivalents.
///
/// This is a phrase-based MT dictionary, not a general-purpose lexicon.
/// Every entry is a term or short phrase that appears in the dynamic
/// narration generated by [OfflineNarrator] — danger signs, triage
/// language, feeding guidance, action steps. Entries are ordered from
/// longest phrase to shortest so the translator can use greedy
/// longest-match-first substitution.
///
/// All translations are drafts. The speech bank's reviewed entries take
/// priority; this dictionary fills the gaps for text the narration
/// composes at runtime.
library;

class TranslationEntry {
  const TranslationEntry({
    required this.english,
    required this.hausa,
    required this.twi,
    required this.dagbani,
  });

  final String english;
  final String hausa;
  final String twi;
  final String dagbani;

  String? textFor(String language) => switch (language) {
    'Hausa' => hausa,
    'Twi' => twi,
    'Dagbani' => dagbani,
    _ => null,
  };
}

/// Longest-first ordering matters: the translator greedily matches from
/// the start of each sentence, so 'go to the health facility now' must
/// appear before 'health facility' to avoid a partial match.
abstract final class TranslationDictionary {
  static const List<TranslationEntry> entries = [
    // ---- Multi-word structural phrases ----
    TranslationEntry(
      english: 'go to the health facility now',
      hausa: 'ku tafi asibiti yanzu',
      twi: 'kɔ ayaresabea ntɛm ara',
      dagbani: 'yi tiŋ bɛ ni kpeeni pam',
    ),
    TranslationEntry(
      english: 'go to the health facility at once',
      hausa: 'ku tafi asibiti nan take',
      twi: 'kɔ ayaresabea ntɛm ara',
      dagbani: 'yi tiŋ bɛ ni kpeeni pam',
    ),
    TranslationEntry(
      english: 'contact a health worker today',
      hausa: 'ku tuntuɓi ma\'aikacin lafiya yau',
      twi: 'kɔtɔɔbɔ ɔyaredfo nnɛ',
      dagbani: 'ti kpeeni bɛ ni sɔŋsi ŋɔ',
    ),
    TranslationEntry(
      english: 'health facility',
      hausa: 'asibiti',
      twi: 'ayaresabea',
      dagbani: 'kpeeni',
    ),
    TranslationEntry(
      english: 'health worker',
      hausa: 'ma\'aikacin lafiya',
      twi: 'ɔyaredfo',
      dagbani: 'kpeeni niriba',
    ),
    TranslationEntry(
      english: 'care plan',
      hausa: 'shirin kula',
      twi: 'dwumadi a wɔbɛdi',
      dagbani: 'sɔŋsi piligu',
    ),
    TranslationEntry(
      english: 'danger signs',
      hausa: 'alamun haɗari',
      twi: 'ɔhaw ho nsɛnkyerɛnne',
      dagbani: 'bɛnkpɛnli zaɣa',
    ),
    TranslationEntry(
      english: 'follow-up',
      hausa: 'sake duba',
      twi: 'san hwɛ bio',
      dagbani: 'labi buɣisi',
    ),
    TranslationEntry(
      english: 'urgent referral',
      hausa: 'gaggawar tura',
      twi: 'akɔne ntɛm mu',
      dagbani: 'kpeeni tuhi din gbanŋɛ',
    ),
    TranslationEntry(
      english: 'clinical examination',
      hausa: 'binciken likita',
      twi: 'ayarehwɛ',
      dagbani: 'kpeeni baŋsi',
    ),
    // ---- Assessment and triage ----
    TranslationEntry(
      english: 'priority',
      hausa: 'fiye ma',
      twi: 'ehia paa',
      dagbani: 'zaɣibu',
    ),
    TranslationEntry(
      english: 'urgent',
      hausa: 'na gaggawa',
      twi: 'ntɛm paa',
      dagbani: 'din gbanŋɛ',
    ),
    TranslationEntry(
      english: 'contact today',
      hausa: 'tuntuɓa yau',
      twi: 'kɔtɔɔbɔ nnɛ',
      dagbani: 'sɔŋsi ŋɔ',
    ),
    TranslationEntry(
      english: 'routine',
      hausa: 'na yau da kullum',
      twi: 'deɛ ɛyɛ daa',
      dagbani: 'din bɛ ni kɔɔ',
    ),
    TranslationEntry(
      english: 'assessment',
      hausa: 'bincike',
      twi: 'nhwehwɛmu',
      dagbani: 'baŋsi',
    ),
    TranslationEntry(
      english: 'findings',
      hausa: 'sakamakon bincike',
      twi: 'neɛ wɔn ahunu',
      dagbani: 'di puuni',
    ),
    TranslationEntry(
      english: 'missing information',
      hausa: 'bayanan da suka ɓace',
      twi: 'nsɛm a wɔnni',
      dagbani: 'sɔŋsi shɛli',
    ),
    TranslationEntry(
      english: 'incomplete',
      hausa: 'bai cika ba',
      twi: 'ɛnnyɛ pɛpɛɛpɛ',
      dagbani: 'di m pa zuɣu',
    ),
    // ---- Danger signs (individual) ----
    TranslationEntry(
      english: 'fever',
      hausa: 'zazzabi',
      twi: 'hyew',
      dagbani: 'kpaliŋ',
    ),
    TranslationEntry(
      english: 'high fever',
      hausa: 'zazzabi mai tsanani',
      twi: 'hyew denden',
      dagbani: 'kpaliŋ pam',
    ),
    TranslationEntry(
      english: 'fits',
      hausa: 'tautsiya',
      twi: 'sɛsɛa',
      dagbani: 'zuɣa',
    ),
    TranslationEntry(
      english: 'vomits everything',
      hausa: 'yana fitar da abinci gaba ɗaya',
      twi: 'ɔto aduane nyinaa',
      dagbani: 'o yiɣiri zaŋ',
    ),
    TranslationEntry(
      english: 'vomiting',
      hausa: 'amashi',
      twi: 'ɔtotoe',
      dagbani: 'yiɣiri',
    ),
    TranslationEntry(
      english: 'cannot drink or breastfeed',
      hausa: 'ba zai iya sha ko shan nono ba',
      twi: 'ɔntumi nnom nsuo anaasɛ ɔnnom nono',
      dagbani: 'o nu tana bee ka o nu tana',
    ),
    TranslationEntry(
      english: 'very sleepy',
      hausa: 'barci mai yawa',
      twi: 'ɔda dɛ paa',
      dagbani: 'o wum kpibu',
    ),
    TranslationEntry(
      english: 'hard to wake',
      hausa: 'ya yi wuya a farka',
      twi: 'ɛyɛ den sɛ wobɛbue no',
      dagbani: 'o ti bini',
    ),
    TranslationEntry(
      english: 'breathes fast',
      hausa: 'numfashi mai sauri',
      twi: 'ne home yɛ ntɛm',
      dagbani: 'o ɣiri tɔɣi',
    ),
    TranslationEntry(
      english: 'difficulty breathing',
      hausa: 'wahalar numfashi',
      twi: 'ɛyɛ no den na ɔhome',
      dagbani: 'o maani nɔri ŋɔ zaɣa',
    ),
    TranslationEntry(
      english: 'blood in the stool',
      hausa: 'jini a cikin latto',
      twi: 'mogya wɔ ne dua mu',
      dagbani: 'kpeeni nɔɔri',
    ),
    TranslationEntry(
      english: 'bleeding',
      hausa: 'zubar da jini',
      twi: 'mogya re gu',
      dagbani: 'kɔbigu',
    ),
    TranslationEntry(
      english: 'severe headache',
      hausa: 'ciwon kai mai ƙarfi',
      twi: 'ne ti yaw den paa',
      dagbani: 'o ti m bɛ laɣim pam',
    ),
    TranslationEntry(
      english: 'severe belly pain',
      hausa: 'ciwon ciki mai ƙarfi',
      twi: 'ne yafunu yaw den paa',
      dagbani: 'o ti kɔbigu taba pam',
    ),
    TranslationEntry(
      english: 'not feeding well',
      hausa: 'ba ya ci da kyau',
      twi: 'ɔnnom nono yie',
      dagbani: 'o nu tana',
    ),
    TranslationEntry(
      english: 'cord is red',
      hausa: 'makogwaronsa ta yi ja',
      twi: 'ne pampɔn no ayɛ kɔkɔɔ',
      dagbani: 'o tuli kpamba ti kɔbigu',
    ),
    TranslationEntry(
      english: 'yellow hands or feet',
      hausa: 'tafafunsa ko ƙafafunsa sun yi rawaya',
      twi: 'ne nsa ase ne nan ase ayɛ abere',
      dagbani: 'o ti ɣari yaa-ŋa bee nini',
    ),
    TranslationEntry(
      english: 'feels very hot',
      hausa: 'jikinsa ya yi zafi sosai',
      twi: 'ne nipadua ayɛ hyew paa',
      dagbani: 'o ti yɛɣiri pam',
    ),
    TranslationEntry(
      english: 'feels very cold',
      hausa: 'jikinsa ya yi sanyi sosai',
      twi: 'ne nipadua ayɛ serew paa',
      dagbani: 'o ti bini pam',
    ),
    // ---- Feeding and nutrition ----
    TranslationEntry(
      english: 'breastfeeding',
      hausa: 'shayar da nono',
      twi: 'nono sa',
      dagbani: 'biɛhigu nu',
    ),
    TranslationEntry(
      english: 'breastmilk',
      hausa: 'nonon mama',
      twi: 'nono',
      dagbani: 'maŋ nu',
    ),
    TranslationEntry(
      english: 'porridge',
      hausa: 'kunu',
      twi: 'nkate ankokɔ',
      dagbani: 'saɣim',
    ),
    TranslationEntry(
      english: 'groundnut paste',
      hausa: 'gidagun gyada',
      twi: 'nkate nkwan',
      dagbani: 'ŋmahiŋ piili',
    ),
    TranslationEntry(
      english: 'feeding',
      hausa: 'ci',
      twi: 'aduane sa',
      dagbani: 'nu',
    ),
    TranslationEntry(
      english: 'nutrition',
      hausa: 'abinci mai gina jiki',
      twi: 'aduane pa',
      dagbani: 'nu sɔŋsi',
    ),
    // ---- Actions and steps ----
    TranslationEntry(
      english: 'what to do next',
      hausa: 'me za a yi na gaba',
      twi: 'deɛ ɛsɛ sɛ yɛdi so',
      dagbani: 'bɛ ni ŋɔ din nyɛ',
    ),
    TranslationEntry(
      english: 'steps to follow',
      hausa: 'matakan da za a bi',
      twi: 'ananse a ɛsɛ sɛ yɛdi so',
      dagbani: 'sɔŋsi shɛŋa bɛ ni ŋɔ',
    ),
    TranslationEntry(
      english: 'give',
      hausa: 'ba',
      twi: 'ma',
      dagbani: 'ti',
    ),
    TranslationEntry(
      english: 'keep doing',
      hausa: 'ci gaba da yin',
      twi: 'toa so di',
      dagbani: 'zaŋ kpɛhiri',
    ),
    TranslationEntry(
      english: 'do not wait',
      hausa: 'kar ku jira',
      twi: 'ntwɛn',
      dagbani: 'di mali kpeenim',
    ),
    TranslationEntry(
      english: 'check again tomorrow',
      hausa: 'sake duba gobe',
      twi: 'san hwɛ anɔpa',
      dagbani: 'labi buɣisi abinsi',
    ),
    TranslationEntry(
      english: 'do not treat it as a reassuring result',
      hausa: 'kar ku ɗauka sakamako mai tausayi ne',
      twi: 'mfa nni dwuma sɛ ɛyɛ ade pa',
      dagbani: 'di mali niŋ sɔŋsi zuɣu',
    ),
    // ---- Body and conditions ----
    TranslationEntry(
      english: 'child',
      hausa: 'yaro',
      twi: 'akwadaa',
      dagbani: 'bini',
    ),
    TranslationEntry(
      english: 'baby',
      hausa: 'jariri',
      twi: 'abofra ketewa',
      dagbani: 'bini kpalansi',
    ),
    TranslationEntry(
      english: 'mother',
      hausa: 'uwa',
      twi: 'ɛna',
      dagbani: 'maŋ',
    ),
    TranslationEntry(
      english: 'pregnant',
      hausa: 'ciki',
      twi: 'ɔokafo',
      dagbani: 'o bɛ ni tuhi',
    ),
    TranslationEntry(
      english: 'cord',
      hausa: 'makogwaro',
      twi: 'pampɔn',
      dagbani: 'tuli',
    ),
    TranslationEntry(
      english: 'stool',
      hausa: 'latto',
      twi: 'dua',
      dagbani: 'nɔɔri',
    ),
    TranslationEntry(
      english: 'today',
      hausa: 'yau',
      twi: 'nnɛ',
      dagbani: 'ŋɔ',
    ),
    TranslationEntry(
      english: 'tomorrow',
      hausa: 'gobe',
      twi: 'anɔpa',
      dagbani: 'abinsi',
    ),
    TranslationEntry(
      english: 'advice',
      hausa: 'shawara',
      twi: 'afotu',
      dagbani: 'sɔŋsi yɛltɔɣa',
    ),
    TranslationEntry(
      english: 'reason',
      hausa: 'dalili',
      twi: 'entideɛ',
      dagbani: 'zugiri',
    ),
    TranslationEntry(
      english: 'family',
      hausa: 'iyali',
      twi: 'abusuapɔn',
      dagbani: 'yili',
    ),
  ];

  /// Entries sorted longest-English-first for greedy matching.
  static final List<TranslationEntry> _byLength = List.of(entries)
    ..sort((a, b) => b.english.length.compareTo(a.english.length));

  static List<TranslationEntry> get byLength => List.unmodifiable(_byLength);
}
