#!/usr/bin/env python3
"""Generate high-quality speech banks using Piper/VITS models trained on
real native speakers, replacing the flat MMS VITS audio.

Models:
  - Hausa:  adab-tech/murya-piper-hausa-tts (8 speakers, WAXAL, 24 kHz, Kano dialect)
  - Twi:    michsethowusu/stable-twi-tts     (12 voices, 327h broadcast, 22 kHz, IPA)

Usage:
    pip install piper-tts onnxruntime soundfile huggingface_hub
    python tool/generate_piper_speech.py hausa
    python tool/generate_piper_speech.py twi
    python tool/generate_piper_speech.py all

Output:
    assets/audio/hausa_piper/<id>.wav   (24 kHz mono PCM16)
    assets/audio/hausa_piper/manifest.json
    assets/audio/hausa_piper/PROVENANCE.md
    assets/audio/twi_piper/<id>.wav    (22.05 kHz mono PCM16)
    assets/audio/twi_piper/manifest.json
    assets/audio/twi_piper/PROVENANCE.md

Prerequisite: download the Piper model ONNX + config from HuggingFace.
    huggingface-cli download adab-tech/murya-piper-hausa-tts --local-dir models/murya_hausa
    huggingface-cli download michsethowusu/stable-twi-tts --local-dir models/stable_twi
"""

from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "assets" / "audio"
MODELS = REPO_ROOT / "models"

# ─── Speaker/voice selections (ML expert picks) ─────────────────────────────────

# Murya Hausa: 8 speakers (4 male, 4 female). Speaker IDs 0-7.
# Speaker 0 = "Malam Garba" (male, authoritative — good for health instructions)
HAUSA_CONFIG = {
    "name": "hausa_piper",
    "model_dir": MODELS / "murya_hausa",
    "model_file": "model.onnx",
    "config_file": "model.onnx.json",
    "upstream": "adab-tech/murya-piper-hausa-tts",
    "dataset": "Google WAXAL (CC-BY-4.0)",
    "license": "CC-BY-NC-SA-4.0",
    "speaker_id": 0,  # Malam Garba (male, Standard Kano)
    "sample_rate": 24000,
    "language": "Hausa",
    "description": "Murya — multi-speaker Hausa (WAXAL, 24 kHz)",
}

# Stable Twi: 12 voices (twi-1 through twi-12).
# twi-6 = best pure-Twi voice (26.8% phoneme error, floor 25.9%)
TWI_CONFIG = {
    "name": "twi_piper",
    "model_dir": MODELS / "stable_twi",
    "model_file": "model.onnx",
    "config_file": "model.onnx.json",
    "upstream": "michsethowusu/stable-twi-tts",
    "dataset": "Ghanaian broadcast (327h, CC-BY-NC-4.0)",
    "license": "CC-BY-NC-4.0",
    "speaker_id": 5,  # twi-6 (0-indexed: 5) — best pure Twi
    "sample_rate": 22050,
    "language": "Twi",
    "description": "Stable-Twi — IPA-driven Piper VITS (327h, 22 kHz)",
}

CONFIGS = {"hausa": HAUSA_CONFIG, "twi": TWI_CONFIG}

# ─── The scripts (must mirror speech_bank.dart exactly) ─────────────────────────
# These are loaded from the existing MMS manifest if available, or defined here.

def load_phrases(bank_name: str) -> dict[str, str]:
    """Load the phrase map from the existing MMS manifest or define fallback."""
    # Try to read from existing manifest (generated by the old script)
    mms_name = bank_name.replace("_piper", "_mms")
    manifest_path = ASSETS / mms_name / "manifest.json"
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
        # manifest format: {id: {text: ..., duration_s: ...}}
        return {k: v["text"] for k, v in manifest.items() if "text" in v}
    # Fallback: read from the Dart source (requires parsing, not done here)
    raise FileNotFoundError(
        f"No manifest found at {manifest_path}. "
        "Run the original MMS generator first to create it."
    )


def synthesize_piper(
    text: str,
    model,
    config: dict,
    speaker_id: int,
    length_scale: float = 1.0,
    noise_scale: float = 0.667,
    noise_w_scale: float = 0.8,
) -> np.ndarray:
    """Synthesize audio using a loaded Piper ONNX model."""
    import pyphen

    # Piper phonemization: espeak-ng based
    try:
        from piper.phonemize_espeak import phonemize_espeak
    except ImportError:
        # Fallback for newer piper versions
        from piper import PiperVoice
        raise ImportError(
            "piper.phonemize_espeak not found. Install: pip install piper-tts"
        )

    lang_code = "ha" if config["language"] == "Hausa" else "ak"  # Akan for Twi

    # Get phonemes from espeak-ng
    phonemes_list = phonemize_espeak(text, lang_code)

    if not phonemes_list:
        return np.array([], dtype=np.float32)

    # Convert phonemes to IDs using model's phoneme_id_map
    phoneme_ids = []
    for phonemes in phonemes_list:
        for ph in phonemes:
            if ph in config["_phoneme_id_map"]:
                phoneme_ids.append(config["_phoneme_id_map"][ph])
            else:
                # Unknown phoneme — skip
                pass

    if not phoneme_ids:
        return np.array([], dtype=np.float32)

    # Run ONNX inference
    import onnxruntime as ort

    session: ort.InferenceSession = config["_session"]

    # Get input/output names
    input_names = [inp.name for inp in session.get_inputs()]
    output_names = [out.name for out in session.get_outputs()]

    # Build input dict based on model's expected inputs
    text_tensor = np.array([phoneme_ids], dtype=np.int64)
    text_len = np.array([len(phoneme_ids)], dtype=np.int64)
    sid = np.array([speaker_id], dtype=np.int64)
    ls = np.array([length_scale], dtype=np.float32)
    ns = np.array([noise_scale], dtype=np.float32)
    nws = np.array([noise_w_scale], dtype=np.float32)

    feed = {}
    for name in input_names:
        if "text" in name and "length" not in name:
            feed[name] = text_tensor
        elif "text_lengths" in name or ("length" in name and "scale" not in name):
            feed[name] = text_len
        elif "sid" in name or "speaker" in name:
            feed[name] = sid
        elif "length_scale" in name:
            feed[name] = ls
        elif "noise_scale" in name and "w" not in name:
            feed[name] = ns
        elif "noise_w" in name:
            feed[name] = nws

    outputs = session.run(output_names, feed)
    audio = outputs[0].squeeze()

    # Normalize to int16 range
    if audio.dtype == np.float32:
        audio = np.clip(audio, -1.0, 1.0)
        audio = (audio * 32767).astype(np.int16)

    return audio


def generate_bank(config: dict, phrases: dict[str, str]) -> None:
    """Generate all clips for one language bank."""
    import onnxruntime as ort

    name = config["name"]
    output_dir = ASSETS / name
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load model
    model_path = config["model_dir"] / config["model_file"]
    config_path = config["model_dir"] / config["config_file"]

    if not model_path.exists():
        print(f"ERROR: Model not found at {model_path}")
        print(f"  Download: huggingface-cli download {config['upstream']} --local-dir {config['model_dir']}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  Generating: {config['language']} ({name})")
    print(f"  Model:      {config['upstream']}")
    print(f"  Voice:      speaker_id={config['speaker_id']}")
    print(f"  Output:     {output_dir}")
    print(f"  Clips:      {len(phrases)}")
    print(f"{'='*60}\n")

    # Load model config (phoneme_id_map, sample_rate, etc.)
    with open(config_path) as f:
        model_cfg = json.load(f)

    config["_phoneme_id_map"] = model_cfg.get("phoneme_id_map", {})
    if not config["_phoneme_id_map"]:
        # Piper models store it differently
        config["_phoneme_id_map"] = {
            ch: i for i, ch in enumerate(
                model_cfg.get("phoneme_id_map", ["_", " ", "!", '"', "'"])
            )
        }

    # Create ONNX session
    opts = ort.SessionOptions()
    opts.inter_op_num_threads = 2
    opts.intra_op_num_threads = 4
    session = ort.InferenceSession(str(model_path), opts, providers=["CPUExecutionProvider"])
    config["_session"] = session

    sample_rate = model_cfg.get("audio", {}).get("sample_rate", config["sample_rate"])

    # Generate each clip
    manifest = {}
    success_count = 0
    for clip_id, text in sorted(phrases.items()):
        wav_path = output_dir / f"{clip_id}.wav"
        try:
            audio = synthesize_piper(text, session, config, config["speaker_id"])
            if audio.size == 0:
                print(f"  ⚠ {clip_id}: empty output, skipping")
                continue
            sf.write(str(wav_path), audio, sample_rate, subtype="PCM_16")
            duration = len(audio) / sample_rate
            manifest[clip_id] = {
                "text": text,
                "duration_s": round(duration, 2),
                "sample_rate": sample_rate,
            }
            print(f"  ✓ {clip_id} ({duration:.1f}s)")
            success_count += 1
        except Exception as e:
            print(f"  ✗ {clip_id}: {e}")

    # Write manifest
    manifest_path = output_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    # Write provenance
    prov_path = output_dir / "PROVENANCE.md"
    with open(prov_path, "w") as f:
        f.write(f"# {config['language']} Speech Bank ({name})\n\n")
        f.write(f"**Model**: {config['upstream']}\n")
        f.write(f"**Architecture**: {config['description']}\n")
        f.write(f"**Speaker ID**: {config['speaker_id']}\n")
        f.write(f"**Sample rate**: {sample_rate} Hz\n")
        f.write(f"**Training data**: {config['dataset']}\n")
        f.write(f"**License**: {config['license']}\n")
        f.write(f"**Generated**: {_dt.datetime.now().isoformat()}\n\n")
        f.write("## Notes\n\n")
        f.write("These clips are synthesized drafts using a neural TTS model trained\n")
        f.write("on real native speaker audio. They are NOT studio recordings.\n")
        f.write("Translation accuracy requires native-speaker clinical review.\n\n")
        f.write("## Regeneration\n\n")
        f.write(f"```\npip install piper-tts onnxruntime soundfile\n")
        f.write(f"huggingface-cli download {config['upstream']} --local-dir {config['model_dir']}\n")
        f.write(f"python tool/generate_piper_speech.py {config['language'].lower()}\n")
        f.write("```\n")

    print(f"\n  Generated {success_count}/{len(phrases)} clips")
    print(f"  Output: {output_dir}")
    print(f"  Manifest: {manifest_path}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print(f"Available: {', '.join(CONFIGS.keys())}, all")
        sys.exit(0)

    target = sys.argv[1].lower()
    targets = list(CONFIGS.keys()) if target == "all" else [target]

    for name in targets:
        if name not in CONFIGS:
            print(f"ERROR: Unknown language '{name}'. Available: {', '.join(CONFIGS.keys())}")
            sys.exit(1)
        config = CONFIGS[name]
        # Determine bank folder to read phrases from
        bank = f"{name}_mms"  # e.g. "hausa_mms"
        try:
            phrases = load_phrases(config["name"])
        except FileNotFoundError:
            # Try reading from the MMS folder directly
            phrases = load_phrases(bank.replace("_mms", "_piper"))
        generate_bank(config, phrases)

    print("\n" + "="*60)
    print("  Done! Update pubspec.yaml and speech_bank.dart to use")
    print("  the new *_piper/ folders instead of *_mms/.")
    print("  Run: flutter clean && flutter pub get && flutter build")
    print("="*60)


if __name__ == "__main__":
    main()
